### ISSUE TITLE
gitbook repo sync configuration

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/plasmdocs#44]
Some times, I encounter an error while trying to connect to the docs page via this URL https://docs.plasmnet.io/

![connection-error](https://user-images.githubusercontent.com/40356749/104462222-a050dd00-55f3-11eb-86e3-91a76490ef7b.jpg)

It looks like there is an error with the domain or an issue with GitHub pages integration.
![plasm-docs](https://user-images.githubusercontent.com/40356749/104462391-dd1cd400-55f3-11eb-8bca-b007a63bb01a.jpg)

If this doc is hosted via Gitbook, there is an option that allows GitHub bidirectional integration, I suggest using that which will allow us to only use MarkDown files without any self-hosting burdens or use GitHub pages (details: <https://docs.gitbook.com/integrations/github#setup-the-github-integration>)

**Comment by satellitex** [comment]
Re-configured GitBook integration. Also, docs.plasmnet.io is now routed by `hosting.gitbook.com`. So applying changes to the GitBook side will cause the documentation site to be updated.
